### PR TITLE
Add linux ci

### PR DESCRIPTION
**Pull request by cooljeanius**
Add GitHub CI

### CODE REVIEW

**Comment by cooljeanius** [comment]
Can't even see what the error was due to "This step has been truncated due to its large size. Download the full logs from the menu once the workflow run has completed," and tbh if it's going to be like that every time, I don't really want to bother...

**Comment by cooljeanius** [comment]
actually wait, I've got an idea

**Comment by talregev** [comment]
You are welcome.
Can you create a PR in the original repo?

**Comment by cooljeanius** [comment]
> You are welcome. Can you create a PR in the original repo?

Nope, GCC has its own way of doing things. Although it'd be cool if we could get something like git's "gitgitgadget" set up: https://github.com/gitgitgadget/gitgitgadget

**Comment by talregev** [comment]
I already sent my patch to the official mailing list. If you open a PR in the original repo, I can send it too for you. Or I can send you my email and you will change small details that will fit you. 
Anyway The PR is not for official repo, it is for other people that can use your changes.

**Comment by cooljeanius** [comment]
> I already sent my patch to the official mailing list. If you open a PR in the original repo, I can send it too for you. Or I can send you my email and you will change small details that will fit you. Anyway The PR is not for official repo, it is for other people that can use your changes.

The upstream repo doesn't work by PR though. I mean I guess I can send my updated version of the file to the mailing list as well, but I doubt it will be accepted; upstream has a pretty consistent "no GitHub" stance...

**Comment by talregev** [comment]
When you leave a PR, it not for upstream. It for all the other. Like I left the PR, and you continue my PR because of that.

**Comment by talregev** [comment]
You can also leave a patch in the mailing list. You can do both! :)

**Comment by cooljeanius** [comment]
talregev/gcc#3 ?

**Comment by talregev** [comment]
I meant a PR for upstream:
https://github.com/gcc-mirror/gcc

**Comment by cooljeanius** [comment]
> I meant a PR for upstream: [gcc-mirror/gcc](https://github.com/gcc-mirror/gcc)

If you merge it into the branch you used to create gcc-mirror/gcc#88, the changes will show up there as well

**Pull request merged**
